[build]
  # Folder yang akan di-publish (frontend)
  publish = "public"
  
  # Folder untuk serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# CORS headers untuk API endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://exxpensettracker.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect rules (optional)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200